Ext.define('Rat.model.risk.CorporateAction', {
    extend: 'Ext.data.Model',
    fields: [{
    	name: 'originalMessage',
    	type: 'string'
    }, {
    	name: 'corporateActionReference',
    	type: 'string'
    }, {
    	name: 'senderReference',
    	type: 'string'
    }, {
    	name: 'eventType',
    	type: 'string'
    }, {
    	name: 'eventOptionType',
    	type: 'string'
    }, {
    	name: 'securitySedolCode',
    	type: 'string'
    }, {
    	name: 'earliestEventDate',
    	type: 'date'
    }, {
    	name: 'earliestOptionDate',
    	type: 'date'
    }, {
    	name: 'latestOptionDate',
    	type: 'date'
    }, {
    	name: 'exDate',
    	type: 'date'
    }, {
    	name: 'recordDate',
    	type: 'date'
    }, {
    	name: 'minimumSecurityQuantity',
    	type: 'int'
    }, {
    	name: 'maximumSecurityQuantity',
    	type: 'int'
    }, {
    	name: 'offeror',
    	type: 'string'
    }, {
    	name: 'eventStage',
    	type: 'string'
    }, {
    	name: 'warrantParity',
    	type: 'float'
    }, {
    	name: 'options',
    	type: 'auto'
    }]
});